t = int(input('Digite um numero para ver a sua tabuada: '))
print('-' * 20)
print('{} * {:2}  = {}'.format(t, 1, t*1))
print('{} * {:2}  = {}'.format(t, 2, t*2))
print('{} * {:2}  = {}'.format(t, 3, t*3))
print('{} * {:2}  = {}'.format(t, 4, t*4))
print('{} * {:2}  = {}'.format(t, 5, t*5))
print('{} * {:2}  = {}'.format(t, 6, t*6))
print('{} * {:2}  = {}'.format(t, 7, t*7))
print('{} * {:2}  = {}'.format(t, 8, t*8))
print('{} * {:2}  = {}'.format(t, 9, t*9))
print('{} * {:2}  = {}'.format(t, 10, t*10))
print('-' * 20)
