frase = str(input('Digite o seu nome completo: ')).strip()
nome = frase.split()
print('Muito Prazer em conhecer-te!')
print('O seu primeiro nome é: {}'.format(nome[0]))
print('O seu ultimo nome é {}'.format(nome[-1]))
